import { useEffect, useMemo, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowDownRight, ArrowRight, ArrowUpRight, CalendarDays, Check, Clock3, Layers3, LoaderCircle, ShoppingBag, Sparkles, TrendingUp, Users, Wallet } from 'lucide-react';
import { GlassButton, GlassCard, GlassPanel, Badge } from '../components/ui';
import AnalyticsChart from '../components/AnalyticsChart';
import ForecastChart from '../components/ForecastChart';
import { createAnalyticsHistory } from '../data/analyticsMock';
import { useInventory } from '../data/InventoryContext';
import { stockQuantity } from '../data/inventoryModel';
import type { ForecastHorizon } from '../data/forecastModel';
import { paymentDay } from '../data/paymentModel';
import { formatKzt } from '../data/orderModel';
import { calculateForecast, forecastDate } from '../utils/forecasting';

export default function Forecasting() {
  const [horizon, setHorizon] = useState<ForecastHorizon>(7);
  const [loading, setLoading] = useState(false);
  const [updated, setUpdated] = useState('');
  const [revision, setRevision] = useState(0);
  const [showAll, setShowAll] = useState(false);
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const { items } = useInventory();
  const today = paymentDay(new Date().toISOString());
  const history = useMemo(() => createAnalyticsHistory(today), [today]);
  const forecast = useMemo(() => calculateForecast(history, items, today, horizon), [history, items, today, horizon, revision]);
  useEffect(() => () => { if (timer.current) clearTimeout(timer.current); }, []);
  const ordering = forecast.recommendations.filter(item => item.action === 'Order').length;
  const peakPeriods = [...forecast.days].sort((a, b) => b.orders - a.orders).slice(0, 3);
  const changeText = `${forecast.change >= 0 ? '+' : ''}${forecast.change.toFixed(1)}% vs weekday baseline`;
  function runForecast() {
    if (loading) return;
    setLoading(true); setUpdated('');
    timer.current = setTimeout(() => { setRevision(value => value + 1); setLoading(false); setUpdated(new Date().toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })); timer.current = null; }, 850);
  }
  return <div className="forecast-page">
    <div className="page-heading"><div><div className="eyebrow">A LITTLE FORESIGHT. A BETTER SERVICE.</div><h1>AI Forecasting</h1><p>Demand predictions and inventory recommendations.</p></div><div className="forecast-heading-actions"><div><span className="forecast-control-label">Forecast Horizon</span><div className="analytics-range" aria-label="Forecast Horizon">{([7, 14, 30] as const).map(value => <GlassButton key={value} disabled={loading} aria-pressed={horizon === value} onClick={() => { setHorizon(value); setUpdated(''); }}>{value} Days</GlassButton>)}</div></div><GlassButton className="primary" onClick={runForecast} disabled={loading}>{loading ? <LoaderCircle size={16} className="forecast-spinner"/> : <Sparkles size={16}/>}{loading ? 'Analyzing…' : 'Run Forecast'}</GlassButton></div></div>
    <div className="forecast-intro"><Badge tone="orange"><Sparkles size={12}/>Forecast model · Prototype</Badge><span>Deterministic demo predictions · current inventory · no external AI</span></div>
    <div className="forecast-run-status" role="status" aria-live="polite">{loading ? <><LoaderCircle size={13} className="forecast-spinner"/>Analyzing demand patterns...</> : updated ? <><Check size={13}/>Forecast updated · {updated}</> : <><CalendarDays size={13}/>{forecastDate(forecast.days[0].date)} – {forecastDate(forecast.days[horizon - 1].date)}</>}</div>
    <div className="stats-grid forecast-kpis">{[{ name: 'Predicted Orders', value: forecast.predictedOrders.toLocaleString(), icon: ShoppingBag, detail: changeText }, { name: 'Expected Revenue', value: formatKzt(forecast.revenue), icon: Wallet, detail: 'Based on historical paid order value' }, { name: 'Expected Guests', value: forecast.guests.toLocaleString(), icon: Users, detail: 'Historical guests per order' }, { name: 'Peak Day', value: new Date(`${forecast.peak.date}T12:00:00Z`).toLocaleDateString('en-GB', { weekday: 'long' }), icon: CalendarDays, detail: `${forecast.peak.orders} orders · ${forecastDate(forecast.peak.date).split(' ').slice(1).join(' ')}` }].map((metric, i) => <GlassCard className="stat" key={metric.name}><div className="stat-top"><span>{metric.name}</span><span className="stat-icon"><metric.icon size={19}/></span></div><strong>{metric.value}</strong><small className={i === 0 ? forecast.change < 0 ? 'forecast-negative' : 'positive' : ''}>{i === 0 && <TrendingUp size={12}/>} {metric.detail}</small></GlassCard>)}</div>
    <div className="forecast-grid">
      <GlassCard className="forecast-panel forecast-demand"><div className="card-heading"><div><h2>Demand Forecast</h2><p>Prepare for the rhythm ahead.</p></div><Badge>{horizon} days ahead</Badge></div><div className="forecast-demand-total"><strong>{forecast.predictedOrders}</strong><span>expected orders</span><Badge tone="orange">{changeText}</Badge></div><ForecastChart days={forecast.days}/><div className="forecast-chart-legend"><span><i/>Forecast demand</span><span><i className="baseline"/>Weekday baseline</span><span><i className="band"/>Illustrative range</span></div></GlassCard>
      <GlassCard className="forecast-panel forecast-confidence"><div className="card-heading"><div><h2>Forecast Confidence</h2><p>Prototype indicators, explained.</p></div><Sparkles size={18}/></div><div className="forecast-confidence-orbit" style={{ background: `conic-gradient(#da9677 ${forecast.confidence * 3.6}deg, #ffffff08 0deg)` }}><div><strong>{forecast.confidence}<span>%</span></strong><small>Overall Confidence</small></div></div><p className="forecast-confidence-copy">Based on recent order patterns and historical demo data.</p><div className="forecast-quality"><div><span>Data quality</span><Badge tone="green">{forecast.historyDays >= 28 ? 'Good' : 'Limited'}</Badge></div><div><span>Trend stability</span><Badge>{Math.abs(forecast.multiplier - 1) < .08 ? 'High' : 'Moderate'}</Badge></div><div><span>Inventory coverage</span><Badge tone={ordering ? 'orange' : 'green'}>{ordering > items.length / 2 ? 'Limited' : ordering ? 'Moderate' : 'Good'}</Badge></div></div><p className="analytics-note">Illustrative score and range; not scientifically validated model confidence.</p></GlassCard>
      <GlassCard className="forecast-panel"><div className="card-heading"><div><h2>Revenue Forecast</h2><p>Expected sales, including service.</p></div><Wallet size={18}/></div><div className="analytics-panel-total">{formatKzt(forecast.revenue)}<small>over {horizon} days</small></div><AnalyticsChart points={forecast.days.map(day => ({ label: new Date(`${day.date}T12:00:00Z`).toLocaleDateString('en-GB', horizon === 7 ? { weekday: 'short' } : { day: 'numeric' }), date: forecastDate(day.date), revenue: day.revenue, orders: day.orders }))} title="Revenue Forecast" kind="bars"/><p className="analytics-note">Predicted orders × demo average paid order value, rounded to ₸1,000 per day.</p></GlassCard>
      <GlassCard className="forecast-panel"><div className="card-heading"><div><h2>Predicted Dish Demand</h2><p>Plan your most-loved plates.</p></div><span className="tiny-label">TOP 5</span></div><div className="forecast-dishes">{forecast.dishes.slice(0, 5).map((dish, i) => { const Icon = dish.change < 0 ? ArrowDownRight : ArrowUpRight; return <div key={dish.id}><span className="dish-rank">0{i + 1}</span><div><strong>{dish.name}</strong><small>Expected servings: {dish.quantity}</small><div className="analytics-meter"><i style={{ width: `${dish.quantity / Math.max(1, forecast.dishes[0].quantity) * 100}%` }}/></div></div><span className={dish.change < 0 ? 'forecast-negative' : 'positive'}><Icon size={13}/>{dish.change >= 0 ? '+' : ''}{dish.change.toFixed(1)}%</span></div>; })}</div><p className="analytics-note">Historical menu mix scaled to predicted orders. Trends compare with the weekday baseline.</p></GlassCard>
    </div>
    <GlassPanel className="forecast-panel forecast-inventory"><div className="card-heading"><div><h2>Inventory Recommendations</h2><p>Current stock meets anticipated demand.</p></div><Link to="/inventory" className="button glass-button">View Inventory<ArrowRight size={14}/></Link></div><div className="forecast-inventory-summary"><Badge tone="orange">{ordering} ingredients to order</Badge><span>Needs cover the full {horizon}-day horizon · current quantities update live</span></div><div className="forecast-recommendation-scroll"><table className="forecast-recommendations"><thead><tr><th scope="col">Ingredient</th><th scope="col">Current Stock</th><th scope="col">Predicted Need</th><th scope="col">Recommendation</th><th scope="col">Priority</th></tr></thead><tbody>{forecast.recommendations.slice(0, showAll ? undefined : 8).map(item => <tr key={item.ingredient.id}><td><strong>{item.ingredient.name}</strong><small>{item.ingredient.category}</small></td><td>{stockQuantity(item.ingredient.currentStock)} {item.ingredient.unit}</td><td>{stockQuantity(item.need)} {item.ingredient.unit}</td><td className={item.action === 'Order' ? 'forecast-order-needed' : ''}>{item.action === 'Order' ? `Order +${stockQuantity(item.purchase)} ${item.ingredient.unit}` : item.action}</td><td><Badge tone={item.priority === 'High' ? 'orange' : item.priority === 'Low' ? 'green' : 'neutral'}>{item.priority}</Badge></td></tr>)}</tbody></table></div>{forecast.recommendations.length > 8 && <GlassButton className="subtle forecast-show-all" aria-expanded={showAll} onClick={() => setShowAll(value => !value)}>{showAll ? 'Show fewer ingredients' : `View all ${forecast.recommendations.length} ingredients`}</GlassButton>}<p className="analytics-note">Demo need = predicted orders × illustrative usage per order. Order quantities round up to 0.1 kg/L or whole bottles/pieces. No stock is changed automatically.</p></GlassPanel>
    <div className="forecast-grid forecast-bottom-grid"><GlassCard className="forecast-panel"><div className="card-heading"><div><h2>Forecast Insights</h2><p>Practical signals for your next service.</p></div><Sparkles size={18}/></div><div className="forecast-insights">{forecast.insights.map((insight, i) => <div key={i}><span><Sparkles size={14}/></span><p>{insight}</p></div>)}</div></GlassCard><GlassCard className="forecast-panel"><div className="card-heading"><div><h2>Expected Peak Periods</h2><p>Highest forecast dates in this horizon.</p></div><Clock3 size={18}/></div><div className="forecast-peak-periods">{peakPeriods.map(day => <div key={day.date}><span className="forecast-timeline-dot"/><div><strong>{forecastDate(day.date)}</strong><small>{String(Math.max(0, forecast.peakHour - 1)).padStart(2, '0')}:00 – {String(Math.min(23, forecast.peakHour + 1)).padStart(2, '0')}:00</small></div><Badge tone="orange">{day.orders >= forecast.peak.orders ? 'Very high' : 'High'} demand</Badge></div>)}</div><p className="analytics-note">Time windows use the peak hour from demo historical activity.</p></GlassCard></div>
    <GlassPanel className="forecast-panel forecast-factors"><div className="card-heading"><div><h2>Forecast Factors</h2><p>A transparent view of the inputs.</p></div><Layers3 size={18}/></div><div className="forecast-factor-list">{['Historical Orders', 'Recent Sales Trend', 'Day of Week', 'Popular Dishes', 'Current Inventory'].map(label => <span key={label}><Check size={12}/>{label}</span>)}</div><details className="forecast-about"><summary>About this forecast</summary><p>This prototype uses deterministic forecasting rules and historical demo data to demonstrate the planned demand forecasting workflow. A production version could replace this module with a trained forecasting model.</p><p>The last 28 demo days supply weekday averages, sales trends, menu mix and hourly patterns. The scenario includes a 4% demo planning allowance. InventoryContext supplies current stock only; it does not change demand predictions.</p></details></GlassPanel>
  </div>;
}
